# -*- coding: utf-8 -*-
"""THESIS Margot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2rxUzHHPmn7fOhDOmrnvKz5j2XM3X12
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install linearmodels

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from linearmodels.iv import IV2SLS
from linearmodels.iv import compare
from scipy.stats import chi2

"""# Import datasets and EDA

### 1: Company informations
"""

#Company data
df_company23_24 = pd.read_excel('Company_23-24.xlsx')
df_company21_22 = pd.read_excel('Company_21-22.xlsx')
df_company19_20 = pd.read_excel('Company_19-20.xlsx')
df_company17_18 = pd.read_excel('Company_17-18.xlsx')
df_company15_16 = pd.read_excel('Company_15-16.xlsx')
df_company13_14 = pd.read_excel('Company_13-14.xlsx')
df_company11_12 = pd.read_excel('Company_11-12.xlsx')
df_company9_10 = pd.read_excel('Company_9-10.xlsx')
df_company7_8 = pd.read_excel('Company_7-8.xlsx')
df_company5_6 = pd.read_excel('Company_5-6.xlsx')
df_company3_4 = pd.read_excel('Company_3-4.xlsx')

df_company = pd.concat([df_company23_24, df_company21_22, df_company19_20, df_company17_18, df_company15_16, df_company13_14, df_company11_12, df_company9_10, df_company7_8, df_company5_6, df_company3_4])

df_company = df_company.drop([
    'Investment Round Permid',
    'Firm Investor BEID',
    'Fund Investor BEID',
    "Deal Value\n(USD, Millions)",
    "Avg Equity Per Deal in Search Range\n(USD, Millions)",
    "Avg Equity Per Firm in Search Range\n(USD, Millions)",
    "Avg Equity Per Fund in Search Range\n(USD, Millions)",
    "Sum of Equity Invested in Search Range\n(USD, Millions)",
    "Deal Value\n(USD, Millions).1",
    "Deal Rank Value\n(USD, Millions)",
    "Pure Venture Capital Deals\n('|')"
    ], axis=1)

df_company = df_company.rename(columns={"Unnamed: 0":"company_id", "Investee Company TRBC Economic Sector":"company_industry", "Disclosed Post Round Company Valuation\n(USD, '|')":"post_round_company_valuation", "Investee Company Total Funding Received To Date\n(USD, '|')":"company_total_funding", "Investee Company Founded Date\n('|')":"company_founded_date", "Investment Date\n(:, '|')":"investment_date"})

# EDA
# Basic statistics
print("\n=== Column Information ===")
print(df_company.info())

# Missing and zero values
missing_counts = df_company.isnull().sum()
zero_counts = (df_company == 0).sum()

missing_percent = 100 * missing_counts / len(df_company)
zero_percent = 100 * zero_counts / len(df_company)

missing_df = pd.DataFrame({
    "Missing Count": missing_counts,
    "Missing %": missing_percent,
    "Zero Count": zero_counts,
    "Zero %": zero_percent
}).sort_values(by="Missing %", ascending=False)

print("\n=== Missing and Zero Values by Column ===")
print(missing_df)

# Horizontal bar chart of missing and zero values
plt.figure(figsize=(12,6))
sns.barplot(y=missing_df.index, x=missing_df["Missing %"], color='salmon', label='Missing %')
sns.barplot(y=missing_df.index, x=missing_df["Zero %"], color='lightblue', label='Zero %')

plt.xlabel("Percentage")
plt.ylabel("Columns")
plt.title("Percentage of Missing and Zero Values per Column")
plt.legend()
plt.show()

df_company = df_company[pd.to_numeric(df_company["company_id"], errors="coerce").notnull()]
df_company["company_id"] = df_company["company_id"].astype(int)
df_company = df_company.dropna()

"""### 2: Fund informations"""

#Fund data
df_fund23_24 = pd.read_excel('Fund_23-24.xlsx')
df_fund21_22 = pd.read_excel('Fund_21-22.xlsx')
df_fund19_20 = pd.read_excel('Fund_19-20.xlsx')
df_fund17_18 = pd.read_excel('Fund_17-18.xlsx')
df_fund15_16 = pd.read_excel('Fund_15-16.xlsx')
df_fund13_14 = pd.read_excel('Fund_13-14.xlsx')
df_fund11_12 = pd.read_excel('Fund_11-12.xlsx')
df_fund9_10 = pd.read_excel('Fund_9-10.xlsx')
df_fund7_8 = pd.read_excel('Fund_7-8.xlsx')
df_fund5_6 = pd.read_excel('Fund_5-6.xlsx')
df_fund3_4 = pd.read_excel('Fund_3-4.xlsx')

df_fund = pd.concat([df_fund23_24, df_fund21_22, df_fund19_20, df_fund17_18, df_fund15_16, df_fund13_14, df_fund11_12, df_fund9_10, df_fund7_8, df_fund5_6, df_fund3_4])

df_fund = df_fund.drop([
    'Investment Round Permid',
    "Investee Company Nation\n('|')",
    "Investment Date\n(:, '|')",
    'Investee Company BEID',
    "Avg Equity Per Deal in Search Range\n(USD, Millions)",
    "Avg Equity Per Company in Search Range\n(USD, Millions)",
    "Sum of Equity Invested in Search Range\n(USD, Millions)",
    "Deal Value\n(USD, Millions)",
    "Deal Rank Value\n(USD, Millions)",
    "Pure Venture Capital Deals\n('|')"
    ], axis=1)

df_fund = df_fund.rename(columns={"Fund Investor Organization Id\n('|')":"fund_id", "Fund Investors Total Number Of Deals\n('|')":"fund_total_deals", "Fund Investors Size\n(USD, '|')":"fund_investor_size"})

# EDA
# Basic statistics
print("\n=== Column Information ===")
print(df_fund.info())

# Missing and zero values
missing_counts = df_fund.isnull().sum()
zero_counts = (df_fund == 0).sum()

missing_percent = 100 * missing_counts / len(df_fund)
zero_percent = 100 * zero_counts / len(df_fund)

missing_df = pd.DataFrame({
    "Missing Count": missing_counts,
    "Missing %": missing_percent,
    "Zero Count": zero_counts,
    "Zero %": zero_percent
}).sort_values(by="Missing %", ascending=False)

print("\n=== Missing and Zero Values by Column ===")
print(missing_df)

df_fund = df_fund.dropna()
df_fund = df_fund[pd.to_numeric(df_fund["fund_id"], errors="coerce").notnull()]
df_fund["fund_id"] = df_fund["fund_id"].astype(int)

"""### 3: Deal informations"""

#Deal data
df_deal24 = pd.read_excel('Deal_24.xlsx')
df_deal23 = pd.read_excel('Deal_23.xlsx')
df_deal22 = pd.read_excel('Deal_22.xlsx')
df_deal21 = pd.read_excel('Deal_21.xlsx')
df_deal20 = pd.read_excel('Deal_20.xlsx')
df_deal19 = pd.read_excel('Deal_19.xlsx')
df_deal18 = pd.read_excel('Deal_18.xlsx')
df_deal17 = pd.read_excel('Deal_17.xlsx')
df_deal16 = pd.read_excel('Deal_16.xlsx')
df_deal15 = pd.read_excel('Deal_15.xlsx')
df_deal14 = pd.read_excel('Deal_14.xlsx')
df_deal13 = pd.read_excel('Deal_13.xlsx')
df_deal12 = pd.read_excel('Deal_12.xlsx')
df_deal11 = pd.read_excel('Deal_11.xlsx')
df_deal10 = pd.read_excel('Deal_10.xlsx')
df_deal9 = pd.read_excel('Deal_9.xlsx')
df_deal8 = pd.read_excel('Deal_8.xlsx')
df_deal7 = pd.read_excel('Deal_7.xlsx')
df_deal6 = pd.read_excel('Deal_6.xlsx')
df_deal5 = pd.read_excel('Deal_5.xlsx')
df_deal4 = pd.read_excel('Deal_4.xlsx')
df_deal3 = pd.read_excel('Deal_3.xlsx')

df_deal = pd.concat([df_deal24, df_deal23, df_deal22, df_deal21, df_deal20, df_deal19, df_deal18, df_deal17, df_deal16, df_deal15, df_deal14, df_deal13, df_deal12, df_deal11, df_deal10, df_deal9, df_deal8, df_deal7, df_deal6, df_deal5, df_deal4, df_deal3])

df_deal = df_deal.drop([
    'Investee Company TRBC Economic Sector',
    'Investee Company Name',
    'Investee Company Nation',
    'Round Number',
    'Unnamed: 6',
    'Fund Investor Name',
    "Firm Investor Name",
    "Investor Equity Total\n(USD, Millions)",
    "Disclosed Fund Equity Contribution\n(USD, Millions)",
    "Round Equity Total\n(USD, Millions)",
    "Disclosed Debt Contribution\n(USD, Millions)",
    "Deal Value\n(USD, Millions)",
    "Deal Rank Value\n(USD, Millions)",
    "Pure Venture Capital Deals\n('|')"
    ], axis=1)

df_deal = df_deal.rename(columns={"Investee Company BEID":"company_id", "Fund Investor Organization Id":"fund_id", "Investment Date":"investment_date", "Number Of Investors\n('|')":"number_of_investors"})
df_deal = df_deal.sort_values(by='investment_date', ascending=True)
df_deal['investment_date'] = pd.to_datetime(df_deal['investment_date'])

# EDA
# Basic statistics
print("\n=== Column Information ===")
print(df_deal.info())

# Missing and zero values
missing_counts = df_deal.isnull().sum()
zero_counts = (df_deal == 0).sum()

missing_percent = 100 * missing_counts / len(df_deal)
zero_percent = 100 * zero_counts / len(df_deal)

missing_df = pd.DataFrame({
    "Missing Count": missing_counts,
    "Missing %": missing_percent,
    "Zero Count": zero_counts,
    "Zero %": zero_percent
}).sort_values(by="Missing %", ascending=False)

print("\n=== Missing and Zero Values by Column ===")
print(missing_df)

"""### 4: Joint datas"""

# Data Harmonization
# Copy dataframes to avoid modifying originals
df_company = df_company.copy()
df_deal = df_deal.copy()
df_fund = df_fund.copy()

# Convert date columns to datetime format
df_company['investment_date'] = pd.to_datetime(df_company['investment_date']).dt.date
df_deal['investment_date'] = pd.to_datetime(df_deal['investment_date']).dt.date

# Ensure IDs have the same type
df_company['company_id'] = df_company['company_id'].astype(str)
df_deal['company_id'] = df_deal['company_id'].astype(str)
df_deal['fund_id'] = df_deal['fund_id'].astype(str)
df_fund['fund_id'] = df_fund['fund_id'].astype(str)

# Drop potential duplicates in df_fund
df_fund = df_fund.drop_duplicates(subset='fund_id', keep='last')

# Helper to compute the mode or return NaN
def mode_or_nan(s):
    m = s.mode(dropna=True)
    return m.iloc[0] if not m.empty else np.nan

# Aggregate df_company at company-date level (Because LSEG export often has one line per investor)
company_keys = ['company_id', 'investment_date']

df_company_day = (
    df_company
    .groupby(company_keys, as_index=False)
    .agg({
        'Investee Company Name': 'first',  # or mode_or_nan
        'Investee Company Nation': mode_or_nan,
        'company_industry': mode_or_nan,
        'post_round_company_valuation': 'max',  # take max to capture non-null valuation
        'company_total_funding': 'max',
        'company_founded_date': 'min'  # unique foundation date
    })
)

# Aggregate df_deal at company-date level
deal_keys = ['company_id', 'investment_date']

df_deal_agg = (
    df_deal
    .groupby(deal_keys, as_index=False)
    .agg(
        number_of_investors=('number_of_investors', 'max'),  # reported deal value (repeated)
        number_of_funds=('fund_id', 'nunique'),  # size of the syndicate (number of funds)
    )
)

# Aggregate fund characteristics at company-date level
df_deal_fund = df_deal.merge(
    df_fund[['fund_id', 'fund_investor_size', 'fund_total_deals']],
    on='fund_id', how='left'
)

df_fund_agg = (
    df_deal_fund
    .groupby(deal_keys, as_index=False)
    .agg(
        fund_size_max=('fund_investor_size', 'max'),  # largest investor in the round
        fund_deals_max=('fund_total_deals', 'max')   # most experienced investor
    )
)

# Final merge at company-date level
df_final = (
    df_company_day
    .merge(df_deal_agg, on=deal_keys, how='left')
    .merge(df_fund_agg, on=deal_keys, how='left')
)

df_final = df_final[
    (df_final["company_total_funding"] > 0) &
    (df_final["post_round_company_valuation"] > 0)
]
df_final = df_final.dropna()

# Raw Scatter Plot
plt.figure(figsize=(6,5))
plt.scatter(df_final["company_total_funding"],
            df_final["post_round_company_valuation"],
            alpha=0.3)
plt.xscale("linear")
plt.yscale("linear")
plt.xlabel("Funding")
plt.ylabel("Valuation")
plt.title("Raw Relationship")
plt.show()

# Log-Log Scatter Plot
# Keep only positive values to avoid log(0) errors
df_scatter = df_final[
    (df_final["company_total_funding"] > 0) &
    (df_final["post_round_company_valuation"] > 0)
]

plt.figure(figsize=(6,5))
plt.scatter(np.log(df_scatter["company_total_funding"]),
            np.log(df_scatter["post_round_company_valuation"]),
            alpha=0.3)
plt.xlabel("log(Funding)")
plt.ylabel("log(Valuation)")
plt.title("Log-Log Relationship")
plt.show()

"""# 5. Models computation

### Model 1: Baseline
"""

# Define Variables
y = np.log(df_final["post_round_company_valuation"])
X = np.log(df_final["company_total_funding"])

# Add Constant Term (Intercept β0)
X = sm.add_constant(X)

# Run OLS Regression
model1 = sm.OLS(y, X).fit()

# Disable scientific notation
np.set_printoptions(suppress=True)

# Display Regression Summary
print(model1.summary2(float_format="%.4f"))

"""### Model 2: Adding region and interaction"""

# Dependent Variable
y = np.log(df_final["post_round_company_valuation"])

# Main Independent Variable
X_funding = np.log(df_final["company_total_funding"])

# Create Regional Dummy (1 = EU, 0 = US)
df_final["EU_region"] = (df_final["Investee Company Nation"] != "United States").astype(int)

# Interaction Term: funding * region
X = pd.DataFrame({
    "log_funding": X_funding,
    "EU_region": df_final["EU_region"],
    "interaction": X_funding * df_final["EU_region"]
})

# Add Constant Term
X = sm.add_constant(X)

# Estimate the Model
model2 = sm.OLS(y, X).fit()

# Extract Coefficients
beta0, beta1, beta2, beta3 = model2.params

# Display Separate Equations for US and Europe
print("=== Estimated equations ===")
print(f"US:     log(Valuation) = {beta0:.3f} + {beta1:.3f} * log(Funding)")
print(f"Europe: log(Valuation) = ({beta0:.3f} + {beta2:.3f}) + ({beta1:.3f} + {beta3:.3f}) * log(Funding)")

print(model2.summary2(float_format="%.4f"))

"""### Model 3: Full specification with controls"""

# Dependent Variable
y = np.log(df_final["post_round_company_valuation"])

# Main Independent Variables
X_funding = np.log(df_final["company_total_funding"])
X_investors = df_final["number_of_investors"]

# Construct Company Age as a Control Variable
df_final["company_age"] = (
    pd.to_datetime(df_final["investment_date"]).dt.year
    - pd.to_datetime(df_final["company_founded_date"]).dt.year
).clip(lower=0)  # Set negative values to 0

# Additional Controls at the Fund Level (log-transformed to avoid tiny coefficients)
fund_size = np.log(df_final["fund_size_max"].replace(0, np.nan))  # avoid log(0)
fund_deals = np.log(df_final["fund_deals_max"].replace(0, np.nan))

# Drop rows with NaN values resulting from log(0)
mask = (~fund_size.isna()) & (~fund_deals.isna())
y = y[mask]
X_funding = X_funding[mask]
X_investors = X_investors[mask]
df_final_filtered = df_final.loc[mask]
fund_size = fund_size[mask]
fund_deals = fund_deals[mask]

# Interaction Term: log(funding) × region
interaction = X_funding * df_final_filtered["EU_region"]

# Build X DataFrame Including All Variables
X = pd.DataFrame({
    "log_funding": X_funding,
    "EU_region": df_final_filtered["EU_region"],
    "interaction": interaction,
    "num_investors": X_investors,
    "company_age": df_final_filtered["company_age"],
    "fund_size": fund_size,
    "fund_deals": fund_deals,
    "industry": df_final_filtered["company_industry"],
    "year": pd.to_datetime(df_final_filtered["investment_date"]).dt.year
})

# Add Industry Fixed Effects
X = pd.get_dummies(X, columns=["industry"], drop_first=True)

# Add Year Fixed Effects
X = pd.get_dummies(X, columns=["year"], drop_first=True)

# Convert Boolean Columns to Integers (to avoid OLS errors)
bool_cols = X.select_dtypes(include='bool').columns
X[bool_cols] = X[bool_cols].astype(int)

# Add Constant Term (Intercept)
X = sm.add_constant(X)

# Estimate the OLS Model with Robust Standard Errors (HC3)
model3 = sm.OLS(y, X).fit(cov_type="HC3")  # HC3 = heteroskedasticity-robust SE

# Display results with 4 decimals
print(model3.summary2(float_format="%.4f"))

"""## Other important KPI's

### Summary statistics
"""

# Disable scientific notation globally
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')
np.set_printoptions(suppress=True)

# Select only numeric columns
numeric_cols = df_final.select_dtypes(include=[np.number])

# Exclude EU_region (dummy variable) if present
numeric_cols = numeric_cols.drop(columns=["EU_region"], errors="ignore")

# Compute descriptive statistics (including selected percentiles)
desc = numeric_cols.describe(percentiles=[0.01, 0.5, 0.99]).T

# Rename columns for readability
desc = desc.rename(columns={
    "count": "Count",
    "mean": "Mean",
    "std": "StdDev",
    "min": "Min",
    "50%": "Median",
    "1%": "P1",
    "99%": "P99",
    "max": "Max"
})

# Keep only relevant summary statistics
desc = desc[["Count", "Mean", "Min", "Median", "P1", "P99", "Max", "StdDev"]]

# Format all numbers to fixed-point decimals
desc_formatted = desc.applymap(lambda x: f"{x:,.1f}")

# Display formatted descriptive statistics
desc_formatted

"""### EU vs US startups"""

# Count US vs EU Companies
counts = df_final['EU_region'].value_counts().rename({0: "US", 1: "EU"})

# Convert Counts to Percentages
percentages = df_final['EU_region'].value_counts(normalize=True).rename({0: "US", 1: "EU"}) * 100

print("\nDistribution by Region (%):\n", percentages)

"""### Number of distinct investments"""

# Total Number of Investments
n_investments = len(df_final)

# Number of Unique Startups
n_companies = df_final["company_id"].nunique()

n_investments, n_companies

"""### Number of investments per sector"""

df_final["company_industry"].value_counts()

"""### Number of investments per year"""

# Ensure the investment_date column is in datetime format
df_final['investment_date'] = pd.to_datetime(df_final['investment_date'], errors='coerce')

# Extract the investment year
df_final['investment_year'] = df_final['investment_date'].dt.year

# Count the number of investments per year
investments_per_year = df_final.groupby('investment_year').size()

# Create the bar plot
plt.figure(figsize=(12,6))
investments_per_year.plot(kind='bar', color='skyblue')
plt.title("Number of Investments per Year")
plt.xlabel("Year")
plt.ylabel("Number of Investments")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# 6. Robustness checks

### 1. Exclude outliers
"""

# Filter valid data
df_model = df_final.copy()

# Define bounds for outlier exclusion
low_val = df_model["post_round_company_valuation"].quantile(0.01)
high_val = df_model["post_round_company_valuation"].quantile(0.99)

low_fund = df_model["company_total_funding"].quantile(0.01)
high_fund = df_model["company_total_funding"].quantile(0.99)

# Apply the filter
df_model_outliers = df_model[
    (df_model["post_round_company_valuation"] >= low_val) &
    (df_model["post_round_company_valuation"] <= high_val) &
    (df_model["company_total_funding"] >= low_fund) &
    (df_model["company_total_funding"] <= high_fund)
]

# Estimate the model
y = np.log(df_model_outliers["post_round_company_valuation"])
X = np.log(df_model_outliers["company_total_funding"])
X = sm.add_constant(X)

model_outliers = sm.OLS(y, X).fit(cov_type="HC3")  # robust SE
print(model_outliers.summary2(float_format="%.4f"))

"""### 2. Verification using sub-samples"""

# Disable scientific notation globally
np.set_printoptions(suppress=True)
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

# Run the regression separately for US and Europe
for region, label in [(0, "US"), (1, "Europe")]:
    df_sub = df_model[df_model["EU_region"] == region]

    # Define dependent and independent variables
    y = np.log(df_sub["post_round_company_valuation"])
    X = np.log(df_sub["company_total_funding"])
    X = sm.add_constant(X)

    # Fit robust OLS model
    model_sub = sm.OLS(y, X).fit(cov_type="HC3")

    print(f"\n=== Robustness Check: {label} ===")

    # Get the full model summary
    summary = model_sub.summary2()

    # Convert the summary to text
    summary_as_text = summary.as_text()

    # Loop through each line and replace scientific notation with normal float format
    for line in summary_as_text.split('\n'):
        if 'e+' in line or 'e-' in line:
            try:
                # Try to convert each numeric element to a standard decimal format
                parts = line.split()
                new_parts = []
                for p in parts:
                    try:
                        num = float(p)
                        new_parts.append(f"{num:.4f}")
                    except:
                        new_parts.append(p)
                print(" ".join(new_parts))
            except:
                # If conversion fails, print the original line
                print(line)
        else:
            # Print lines that don’t contain scientific notation
            print(line)

# Disable scientific notation globally
np.set_printoptions(suppress=True)
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

# Split dataset by company size (based on median funding)
threshold = df_model["company_total_funding"].median()
df_small = df_model[df_model["company_total_funding"] <= threshold]
df_large = df_model[df_model["company_total_funding"] > threshold]

# Small Companies
y = np.log(df_small["post_round_company_valuation"])
X = np.log(df_small["company_total_funding"])
X = sm.add_constant(X)

# Fit robust OLS model
model_small = sm.OLS(y, X).fit(cov_type="HC3")

print("\n=== Robustness Check: Small Companies ===")

# Convert summary to text and reformat exponential numbers
summary_small = model_small.summary2().as_text()
for line in summary_small.split('\n'):
    if 'e+' in line or 'e-' in line:
        parts = line.split()
        formatted_parts = []
        for p in parts:
            try:
                num = float(p)
                formatted_parts.append(f"{num:.4f}")
            except:
                formatted_parts.append(p)
        print(" ".join(formatted_parts))
    else:
        print(line)

# Large Companies
y = np.log(df_large["post_round_company_valuation"])
X = np.log(df_large["company_total_funding"])
X = sm.add_constant(X)

# Fit robust OLS model
model_large = sm.OLS(y, X).fit(cov_type="HC3")

print("\n=== Robustness Check: Large Companies ===")

# Convert summary to text and reformat exponential numbers
summary_large = model_large.summary2().as_text()
for line in summary_large.split('\n'):
    if 'e+' in line or 'e-' in line:
        parts = line.split()
        formatted_parts = []
        for p in parts:
            try:
                num = float(p)
                formatted_parts.append(f"{num:.4f}")
            except:
                formatted_parts.append(p)
        print(" ".join(formatted_parts))
    else:
        print(line)

"""### 3. Endogeneity tests"""

# prepare cleaned dataframe
df_iv = df_final.copy()

# create logged variables
df_iv["log_valuation"] = np.log(df_iv["post_round_company_valuation"])
df_iv["log_funding"] = np.log(df_iv["company_total_funding"])

# clean instruments and drop missing
df_iv["fund_size_max"] = df_iv["fund_size_max"].replace([np.inf, -np.inf], np.nan)
df_iv["fund_deals_max"] = df_iv["fund_deals_max"].replace([np.inf, -np.inf], np.nan)
df_iv = df_iv.dropna(subset=["log_valuation", "log_funding", "fund_size_max", "fund_deals_max"])

# Fit OLS using same dataframe
ols = IV2SLS.from_formula("log_valuation ~ 1 + log_funding", data=df_iv).fit()
iv  = IV2SLS.from_formula(
        "log_valuation ~ 1 + [log_funding ~ fund_size_max + fund_deals_max]",
        data=df_iv
      ).fit(cov_type="robust")

# Compare
cmp = compare({"OLS": ols, "IV": iv})
print(cmp)

# Wu-Hausman statistic test
# Regress the endogenous variable on the instruments
first_stage = sm.OLS(df_iv["log_funding"], sm.add_constant(df_iv[["fund_size_max", "fund_deals_max"]])).fit()

# Recording of residuals (what the instruments do not explain)
df_iv["residuals_iv"] = first_stage.resid

# OLS regression of the structural model + residuals
wu_hausman_test = sm.OLS(
    df_iv["log_valuation"],
    sm.add_constant(df_iv[["log_funding", "residuals_iv"]])
).fit(cov_type='HC3')

print(wu_hausman_test.summary2(float_format="%.4f"))

# Re-estimate the IV model (2SLS)
iv_model = IV2SLS.from_formula(
    "log_valuation ~ 1 + [log_funding ~ fund_size_max + fund_deals_max]",
    data=df_iv
).fit(cov_type="robust")

# Retrieve the residuals from the IV model
df_iv["iv_resid"] = iv_model.resids

# Regress the residuals on all instruments (including the constant)
sargan_test = sm.OLS(df_iv["iv_resid"], sm.add_constant(df_iv[["fund_size_max", "fund_deals_max"]])).fit()

# Compute the Sargan test statistic
n = df_iv.shape[0]  # number of observations
R2 = sargan_test.rsquared
sargan_stat = n * R2

# Compute the p-value (chi-square test with k-1 degrees of freedom)
df = df_iv[["fund_size_max", "fund_deals_max"]].shape[1] - 1  # nb of instruments - nb of endogenous variables
p_value = 1 - chi2.cdf(sargan_stat, df)

print("=== Sargan Test for Overidentifying Restrictions ===")
print(f"Sargan statistic: {sargan_stat:.3f}")
print(f"Degrees of freedom: {df}")
print(f"P-value: {p_value:.4f}")

if p_value > 0.05:
    print("\n Instruments are exogenous (fail to reject H0).")
else:
    print("\n Instruments may be endogenous (reject H0).")